### ISSUE TITLE
Add Task Estimation in Scrum Section

### ISSUE THREAD

**Issue by Harmos274** [Harmos274/SQA-Assignment#3]
- [x] Select **5 articles** about task estimation in Scrum and post them as a comment in this issue
- [x] Write down a section explaining our task estimation relying on the articles in the `README.md` in the Task Estimation in Scrum section

**Comment by Basilarc** [comment]
I identified 4 instead of 3 and found an interesting thread on stack exchange :

https://dzone.com/articles/agile-estimation-practice

https://www.mountaingoatsoftware.com/blog/why-agile-teams-should-estimate-at-two-different-levels

https://blog.maqe.com/do-dont-sprint-backlog-estimation-english-cb9be727fde1

https://www.101ways.com/how-to-implement-scrum-in-10-easy-steps-step-2-how-to-estimate-your-product-backlog/

BONUS : (Old stack-exchange thrread on the subject) https://softwareengineering.stackexchange.com/questions/216796/how-to-estimate-tasks-in-scrum

**Comment by BormaPethi** [comment]
#Intro @BormaPethi 
-[Agile estimation](https://dzone.com/articles/agile-estimation-practice)
#How to Estimate Tasks @Basilarc 
-[How to estimate tasks in SCRUM](https://softwareengineering.stackexchange.com/questions/216796/how-to-estimate-tasks-in-scrum)
-[Best way to estimate effort using story point](https://medium.com/serious-scrum/best-way-to-estimate-effort-using-story-point-in-sprint-planning-f43ad2d6fa91)
#Most Common Errors @BormaPethi 
-[12 common mistakes](https://mdalmijn.com/12-common-mistakes-made-when-using-story-points/)
-[Do & don't](https://blog.maqe.com/do-dont-sprint-backlog-estimation-english-cb9be727fde1)
